# FROM microsoft/dotnet:2-sdk
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /home/app

COPY ./*.sln ./
COPY ./*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./${file%.*}/ && mv $file ./${file%.*}/; done

RUN dotnet restore

COPY . .

WORKDIR /home/app/Integration/

ENTRYPOINT ["dotnet", "test", "--verbosity=normal"]